## Practice 1: Creating DataFrames and Series

**Q1.** Create a Pandas Series from a list of numbers: `[10, 20, 30, 40, 50]`.

In [ ]:
import pandas as pd
list=[10,20,30,40,50]
series=pd.Series(list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

**Q2.** Create a Pandas DataFrame from the following dictionary:
```python
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
```

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
dataFrame=pd.DataFrame(data)
print(dataFrame)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 2: Inspecting Data

**Q3.** Given the DataFrame `df`, display the first 3 rows.
```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
```

In [ ]:
#I was confused about df and df2, some questions mentioned df which is required in Q3 to be defined, while others mentioned df2 which was defined in the code cell of Q3 as well, so I considered them as two different data frames.
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
print(df.head(3))

          A         B         C         D
0  0.146668  0.276342 -0.537946 -1.789393
1 -0.010899 -0.595587 -0.313876 -0.150825
2  1.271671 -0.063894  0.133203  1.033272

**Q4.** Print the shape and column names of the DataFrame `df2`.

In [ ]:
print(f"df2 shape is {df2.shape}")
print(f"column name are : {df2.columns}")

df2 shape is (10, 4)
column name are : Index(['A', 'B', 'C', 'D'], dtype='str')

## Practice 3: Selecting and Filtering

**Q5.** Select the column 'Age' from the DataFrame created in Q2 (`df`).

In [8]:
print(dataFrame.Age)

0    25
1    30
2    35
Name: Age, dtype: int64

**Q6.** Filter the DataFrame `df` from Q2 to show only rows where 'Age' is greater than 28.

In [10]:
print(dataFrame[dataFrame.Age>28])

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Practice 4: Handling Missing Data

**Q7.** Given the following DataFrame with missing values, fill the missing values with 0.
```python
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
```

In [11]:
import numpy as np
import pandas as pd
df_nan = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
df_nan.fillna(0)

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

**Q8.** Drop the rows containing any missing values in `df_nan`.

In [12]:
df_nan.dropna()

     A    B
0  1.0  4.0

## Practice 5: Grouping and Aggregation

**Q9.** Group the following DataFrame by 'Department' and calculate the mean salary.
```python
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
```

In [15]:
data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 50000, 70000, 80000, 55000]
}
df_emp = pd.DataFrame(data)
df_emp.groupby('Department').mean()

             Salary
Department
Finance     80000.0
HR          52500.0
IT          65000.0

## Practice 6: Adding and Removing Columns

**Q10.** Add a new column 'Bonus' to `df_emp` which is 10% of the 'Salary'.

In [36]:
df_emp["Bonus"]=df_emp.Salary *0.1
print(df_emp)

  Department  Salary   Bonus
0         IT   60000  6000.0
1         HR   50000  5000.0
2         IT   70000  7000.0
3    Finance   80000  8000.0
4         HR   55000  5500.0

**Q11.** Drop the 'Bonus' column from `df_emp`.

In [37]:
df_emp.drop("Bonus",axis=1,inplace=True)
print(df_emp)

  Department  Salary
0         IT   60000
1         HR   50000
2         IT   70000
3    Finance   80000
4         HR   55000

## Practice 7: Applying Functions

**Q12.** Apply a function or a lambda to convert the 'Department' names to lowercase in `df_emp`.

In [ ]:
df_emp["Department"].str.lower()

0         it
1         hr
2         it
3    finance
4         hr
Name: Department, dtype: str

## Practice 8: Merging and Joining

**Q13.** Create a DataFrame `df_dept` with columns `Department` and `Manager` mapping 'IT' to 'Alice', 'HR' to 'Bob', and 'Finance' to 'Charlie'. Merge it with `df_emp` (from Practice 5) using a left join.

In [44]:
df_dept = pd.DataFrame({'Department': ['IT', 'HR', 'Finance'], 'Manager': ['Alice', 'Bob', 'Charlie']})
merged=pd.merge(df_emp,df_dept,how="left") 
print(merged)

  Department  Salary  Manager
0         IT   60000    Alice
1         HR   50000      Bob
2         IT   70000    Alice
3    Finance   80000  Charlie
4         HR   55000      Bob

## Practice 9: Pivot Tables

**Q14.** Create a pivot table from the merged DataFrame that shows the total (sum) and average (mean) salary for each manager.

In [ ]:
pivot=pd.pivot_table(
    merged,
    values="Salary",#Which its average is to be calculated.
    index="Manager",# The variables which are to be displayed as rows.
    aggfunc=["mean","sum"]#the aggregation function that will evaluate the average and the sum 
    )
print(pivot)

            mean     sum
          Salary  Salary
Manager
Alice    65000.0  130000
Bob      52500.0  105000
Charlie  80000.0   80000

## Practice 10: Advanced Data Manipulation

**Q15.** Given a DataFrame with sales data, calculate the rolling 3-day average of 'Revenue'.
```python
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
```

In [51]:
sales_data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Product': ['A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B'],
    'Revenue': [100, 200, 150, 250, 300, 250, 100, 150, 200, 300]
}
df_sales = pd.DataFrame(sales_data)
df_sales["Rolling 3-day Average of Revenue"]=df_sales["Revenue"].rolling(window=3).mean()
print(df_sales)

        Date Product  Revenue  Rolling 3-day Average of Revenue
0 2023-01-01       A      100                               NaN
1 2023-01-02       B      200                               NaN
2 2023-01-03       A      150                        150.000000
3 2023-01-04       B      250                        200.000000
4 2023-01-05       A      300                        233.333333
5 2023-01-06       A      250                        266.666667
6 2023-01-07       B      100                        216.666667
7 2023-01-08       B      150                        166.666667
8 2023-01-09       A      200                        150.000000
9 2023-01-10       B      300                        216.666667

**Q16.** Find the top 2 highest revenue days for each product from `df_sales`.

In [ ]:
top_2_revenues_indicies=df_sales.groupby("Product")["Revenue"].nlargest(2).index.get_level_values(1)#treturns the indicies where the top 2 revenue of each product are placed
Top_two=df_sales.loc[top_2_revenues_indicies]#retuns the rows of the top two for each product
Top_two=Top_two.drop("Rolling 3-day Average of Revenue",axis=1)#removing the rolling
print(Top_two)#prints : date, product, revenu

        Date Product  Revenue
4 2023-01-05       A      300
5 2023-01-06       A      250
9 2023-01-10       B      300
3 2023-01-04       B      250

**Q17.** Extract the year and month from the 'Date' column in `df_sales` and create two new columns 'Year' and 'Month'.

In [92]:
Year=df_sales["Date"].dt.year
Month=df_sales["Date"].dt.month_name()
df_sales["Year"]=Year
df_sales["Month"]=Month
print(df_sales)

        Date Product  Revenue  Rolling 3-day Average of Revenue  Year    Month
0 2023-01-01       A      100                               NaN  2023  January
1 2023-01-02       B      200                               NaN  2023  January
2 2023-01-03       A      150                        150.000000  2023  January
3 2023-01-04       B      250                        200.000000  2023  January
4 2023-01-05       A      300                        233.333333  2023  January
5 2023-01-06       A      250                        266.666667  2023  January
6 2023-01-07       B      100                        216.666667  2023  January
7 2023-01-08       B      150                        166.666667  2023  January
8 2023-01-09       A      200                        150.000000  2023  January
9 2023-01-10       B      300                        216.666667  2023  January